### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by JmMndz** [juh9870/EXpandableFolder#4]
Hi!

How could I implement a background?
How could I know W and H of skin according to number and arrangement of tiles?
Here it is what a have done so far, but now I want to implement a background to make it easier to read file names.
https://www.deviantart.com/jjmilton/art/EXpandExplore-Full-1-1-934463916

**Comment by JmMndz** [comment]
I just did it:

[MeasureBackground]
Measure=Calc
Formula=(Clamp (MeasureTotalCount, 0, (#ExLimit# - 1)))
IfCondition=(#CURRENTSECTION# < 1)
IfTrueAction=[!SetOption MainBackground W "(#FontSize# * 10.78 * 1)"][!SetOption MainBackground H "(#FontSize# * 10.65 * 1)"]
IfCondition2=(#CURRENTSECTION# = 1)
IfTrueAction2=[!SetOption MainBackground W "(#FontSize# * 10.78 * 2)"][!SetOption MainBackground H "(#FontSize# * 10.65 * 1)"]
IfCondition3=(#CURRENTSECTION# = 2) || (#CURRENTSECTION# = 3)
IfTrueAction3=[!SetOption MainBackground W "(#FontSize# * 10.78 * 2)"][!SetOption MainBackground H "(#FontSize# * 10.65 * 2)"]
IfCondition4=(#CURRENTSECTION# = 4) || (#CURRENTSECTION# = 5)
IfTrueAction4=[!SetOption MainBackground W "(#FontSize# * 10.78 * 3)"][!SetOption MainBackground H "(#FontSize# * 10.65 * 2)"]
IfCondition5=(#CURRENTSECTION# = 6) || (#CURRENTSECTION# = 7) || (#CURRENTSECTION# = 8)
IfTrueAction5=[!SetOption MainBackground W "(#FontSize# * 10.78 * 3)"][!SetOption MainBackground H "(#FontSize# * 10.65 * 3)"]
IfCondition6=(#CURRENTSECTION# = 9) || (#CURRENTSECTION# = 10) || (#CURRENTSECTION# = 11)
IfTrueAction6=[!SetOption MainBackground W "(#FontSize# * 10.78 * 4)"][!SetOption MainBackground H "(#FontSize# * 10.65 * 3)"]
IfCondition7=(#CURRENTSECTION# = 12) || (#CURRENTSECTION# = 13) || (#CURRENTSECTION# = 14) || (#CURRENTSECTION# = 15)
IfTrueAction7=[!SetOption MainBackground W "(#FontSize# * 10.78 * 4)"][!SetOption MainBackground H "(#FontSize# * 10.65 * 4)"]
IfCondition8=(#CURRENTSECTION# = 16) || (#CURRENTSECTION# = 17) || (#CURRENTSECTION# = 18) || (#CURRENTSECTION# = 19)
IfTrueAction8=[!SetOption MainBackground W "(#FontSize# * 10.78 * 5)"][!SetOption MainBackground H "(#FontSize# * 10.65 * 4)"]

[MainBackground]
Meter=Image
SolidColor=#BackgroundColor#,#BackgroundTransparency#
Group=Main

@include=#@#include\tiles.inc

**Comment by juh9870** [comment]
There is an option `Background_Color` in `variables.inc`, use that
