### ISSUE TITLE
Similar project request

### ISSUE THREAD

**Issue by Osiris-Team** [juh9870/EXpandableFolder#5]
Hey @juh9870 and @JmMndz I wanted to ask you to create something similar to EXpandableFolder but that looks something like this and basically replaces the desktop:
![example_layout](https://user-images.githubusercontent.com/59899645/212469912-bd92e675-2a63-47b9-b63c-46cbbadf7b7c.png)
- The "All" tab contains a scrollable list of all installed programs, sorted alphabetically.
- The "Recent" tab contains a list sorted by last opened program first.
- The "Favorites" tab contains a list sorted by most used program first.
- Left-clicking on a program icon should open it. Right-clicking could be harder to implement, so let's skip that for now, but it should do something similar to the regular right-click, or just open its location in the file explorer.

There are some extras that are not included in the picture above:
- Each tab could also have a search bar below its title to search for programs by their names.
- The titles can be smaller, as well as the gaps between the tabs, messed it up a bit there. The titles can also be removed entirely and replaced by the search fields tooltip, like "Search in favorites..." or "Search in all...".
- The sizes for the tabs should be calculated on init and based on the screen size ( - task bar).
- The "Recent" and "Favorites" tabs could additionally contain links to websites (their icons) that open that website in the browser when clicked. They could also contain files, that when clicked open them.
- If the above is implemented it would also make sense to add program/file names below their icons, to differentiate files of the same type.

**Comment by juh9870** [comment]
Switch to Linux (Plasma KDE desktop) and configure it all you want

**Comment by Osiris-Team** [comment]
Thats the thing linux sucks. At least for the stuff I need it for.

**Comment by juh9870** [comment]
Bad luck then. I'm not taking requests. I've only made EXpandableFolder because I personally needed it, and only posted it to GitHub, so I can access it after reinstalling Windows

**Comment by Osiris-Team** [comment]
Yeah guess im in your shoes now. I'll have to do it myself then. Here is the repo: https://github.com/Osiris-Team/BetterDesktop

**Comment by juh9870** [comment]
Good luck. Tho I'm not sure Rainmeter is good for this. Performance would be trash

**Comment by Osiris-Team** [comment]
Thanks. Yeah I have no clue about Rainmeter, but it doesn't look like there is an alternative.
